//! Test HTTP server used by the integration tests in `tests/cli.rs`.
//!
//! Each test calls `TestServer::start()` to get a fresh Axum server bound to a
//! random localhost port. The server exposes a handful of endpoints that
//! reproduce the HTTP behaviors dlm needs to handle (resume, HEAD-405,
//! Content-Disposition, auth, etc.). Server state is per-instance, so tests
//! don't share counters or request logs.

use axum::Router;
use axum::body::Body;
use axum::extract::{OriginalUri, Path, State};
use axum::http::header::{
    ACCEPT_RANGES, AUTHORIZATION, CONTENT_DISPOSITION, CONTENT_LENGTH, CONTENT_RANGE, LOCATION,
    RANGE,
};
use axum::http::{HeaderMap, HeaderValue, Method, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::{any, get};
use std::net::SocketAddr;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::{Arc, Mutex};
use tokio::net::TcpListener;

/// Deterministic 64 KiB body shared across endpoints. Generated by a Knuth
/// multiplicative hash so any byte-order/duplication bug in dlm would show up
/// as a content mismatch (a uniform fill would hide that class of bug).
pub const FILE_BODY: &[u8] = &FILE_BODY_BYTES;
static FILE_BODY_BYTES: [u8; 64 * 1024] = compute_file_body();

const fn compute_file_body() -> [u8; 64 * 1024] {
    let mut bytes = [0u8; 64 * 1024];
    let mut i = 0;
    while i < bytes.len() {
        bytes[i] = (i.wrapping_mul(2_654_435_769) >> 24) as u8;
        i += 1;
    }
    bytes
}

#[derive(Clone)]
struct ServerState {
    /// Remaining 503 responses to send from `/flaky` before it succeeds.
    /// Configured per-test via `TestServer::set_flaky_fails`.
    flaky_remaining: Arc<AtomicU32>,
    /// Last request seen by `/echo-headers`, for tests that want to assert
    /// what dlm actually sent. `std::sync::Mutex` is fine here — the lock is
    /// never held across an `.await`.
    last_echo_headers: Arc<Mutex<Option<HeaderMap>>>,
    /// Origin URL the server is reachable at, e.g. "http://127.0.0.1:12345".
    /// Set once at startup; immutable thereafter, hence `Arc<str>` (no lock).
    origin: Arc<str>,
}

pub struct TestServer {
    state: ServerState,
}

impl TestServer {
    pub async fn start() -> Self {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr: SocketAddr = listener.local_addr().unwrap();

        let state = ServerState {
            flaky_remaining: Arc::new(AtomicU32::new(0)),
            last_echo_headers: Arc::new(Mutex::new(None)),
            origin: Arc::from(format!("http://{addr}")),
        };

        let app = Router::new()
            .route("/file/{name}", get(serve_file))
            .route("/no-range/{name}", get(serve_no_range))
            .route("/reject-head/{name}", any(reject_head_get_works))
            .route("/zero-cl/{name}", any(zero_content_length_head))
            .route("/redirect/{name}", get(redirect_to_file))
            .route("/redirect-no-ext", get(redirect_no_ext))
            .route("/disposition/{name}", get(content_disposition))
            .route("/auth/{name}", get(basic_auth_required))
            .route("/echo-headers", get(echo_headers))
            .route("/flaky", get(flaky))
            .route("/never-found", get(always_404))
            .route("/short/{name}", any(short_body_with_inflated_cl))
            .route("/disposition-star", get(content_disposition_star))
            .route("/check-query/{name}", get(check_query))
            .route("/always-416/{name}", any(always_416))
            .route("/cut-stream/{name}", any(cut_stream_mid_body))
            .route("/stall/{name}", any(stall_before_headers))
            .route("/slow-first-byte/{name}", any(slow_first_byte))
            .with_state(state.clone());

        tokio::spawn(async move {
            axum::serve(listener, app).await.unwrap();
        });

        Self { state }
    }

    pub fn url(&self, path: &str) -> String {
        format!("{}{path}", self.state.origin)
    }

    pub fn last_echo_headers(&self) -> HeaderMap {
        self.state
            .last_echo_headers
            .lock()
            .unwrap()
            .clone()
            .expect("no request recorded on /echo-headers")
    }

    /// Make `/flaky` return 503 the next `n` times, then succeed.
    pub fn set_flaky_fails(&self, n: u32) {
        self.state.flaky_remaining.store(n, Ordering::SeqCst);
    }
}

// ---------- handlers ----------

/// Standard download endpoint: respects Range, advertises Accept-Ranges.
async fn serve_file(Path(_name): Path<String>, headers: HeaderMap) -> Response {
    serve_with_range(FILE_BODY, &headers, true)
}

/// Like `/file/:name` but does not honor Range and does not advertise it.
async fn serve_no_range(Path(_name): Path<String>, headers: HeaderMap) -> Response {
    serve_with_range(FILE_BODY, &headers, false)
}

/// HEAD returns 405; GET works (with Range support).
async fn reject_head_get_works(
    method: Method,
    Path(_name): Path<String>,
    headers: HeaderMap,
) -> Response {
    if method == Method::HEAD {
        return StatusCode::METHOD_NOT_ALLOWED.into_response();
    }
    serve_with_range(FILE_BODY, &headers, true)
}

/// HEAD returns 200 with Content-Length: 0 (a sign HEAD is faked); GET works.
async fn zero_content_length_head(
    method: Method,
    Path(_name): Path<String>,
    headers: HeaderMap,
) -> Response {
    if method == Method::HEAD {
        let mut resp = Response::new(Body::empty());
        resp.headers_mut()
            .insert(CONTENT_LENGTH, HeaderValue::from_static("0"));
        return resp;
    }
    serve_with_range(FILE_BODY, &headers, true)
}

async fn redirect_to_file(Path(name): Path<String>, State(state): State<ServerState>) -> Response {
    redirect(&format!("{}/file/{name}", state.origin))
}

/// 302 to /file/foo.bin — used to verify that dlm follows the redirect to
/// derive the filename when the original URL had no extension.
async fn redirect_no_ext(State(state): State<ServerState>) -> Response {
    redirect(&format!("{}/file/foo.bin", state.origin))
}

/// Returns the body with `Content-Disposition: attachment; filename="<name>"`.
async fn content_disposition(Path(name): Path<String>, headers: HeaderMap) -> Response {
    let mut resp = serve_with_range(FILE_BODY, &headers, true);
    resp.headers_mut().insert(
        CONTENT_DISPOSITION,
        HeaderValue::from_str(&format!("attachment; filename=\"{name}\"")).unwrap(),
    );
    resp
}

/// Requires Basic auth `alice:s3cret`. 401 otherwise.
async fn basic_auth_required(Path(_name): Path<String>, headers: HeaderMap) -> Response {
    let expected = "Basic YWxpY2U6czNjcmV0"; // base64 of "alice:s3cret"
    match headers.get(AUTHORIZATION).and_then(|v| v.to_str().ok()) {
        Some(v) if v == expected => serve_with_range(FILE_BODY, &headers, true),
        _ => StatusCode::UNAUTHORIZED.into_response(),
    }
}

/// Records the request headers (so tests can assert what dlm sent) and
/// returns a small body so the download succeeds.
async fn echo_headers(State(state): State<ServerState>, headers: HeaderMap) -> Response {
    *state.last_echo_headers.lock().unwrap() = Some(headers.clone());
    serve_with_range(b"echoed", &headers, false)
}

/// Returns 503 while `flaky_remaining > 0`, decrementing atomically each call;
/// succeeds afterwards. `fetch_update` keeps the decrement race-free under
/// concurrent requests.
async fn flaky(State(state): State<ServerState>, headers: HeaderMap) -> Response {
    let consumed = state
        .flaky_remaining
        .fetch_update(Ordering::SeqCst, Ordering::SeqCst, |n| {
            if n > 0 { Some(n - 1) } else { None }
        });
    if consumed.is_ok() {
        return StatusCode::SERVICE_UNAVAILABLE.into_response();
    }
    serve_with_range(FILE_BODY, &headers, true)
}

async fn always_404() -> Response {
    StatusCode::NOT_FOUND.into_response()
}

/// HEAD claims `Content-Length: FILE_BODY.len()`; GET serves only half. dlm
/// should detect the mismatch and raise `IncompleteDownload`.
async fn short_body_with_inflated_cl(method: Method, _path: Path<String>) -> Response {
    if method == Method::HEAD {
        return head_metadata(FILE_BODY);
    }
    let half: &[u8] = &FILE_BODY[..FILE_BODY.len() / 2];
    Response::new(Body::from(half))
}

/// Returns the body with an RFC 6266 `filename*=UTF-8''…` parameter that
/// percent-encodes a space. dlm must decode it to `my file.txt`.
async fn content_disposition_star(headers: HeaderMap) -> Response {
    let mut resp = serve_with_range(FILE_BODY, &headers, true);
    resp.headers_mut().insert(
        CONTENT_DISPOSITION,
        HeaderValue::from_static("attachment; filename*=UTF-8''my%20file.txt"),
    );
    resp
}

/// Succeeds only when the request URL carried `?token=abc123` — proves dlm
/// preserved the query string when sending the request.
async fn check_query(
    Path(_name): Path<String>,
    OriginalUri(uri): OriginalUri,
    headers: HeaderMap,
) -> Response {
    if uri.query() == Some("token=abc123") {
        serve_with_range(FILE_BODY, &headers, true)
    } else {
        StatusCode::BAD_REQUEST.into_response()
    }
}

/// HEAD reports the full size; GET sends a small chunk then drops the
/// connection mid-body. Verifies dlm surfaces the failure (rather than
/// hanging) when the server disconnects unexpectedly.
async fn cut_stream_mid_body(method: Method, _path: Path<String>) -> Response {
    if method == Method::HEAD {
        return head_metadata(FILE_BODY);
    }
    let chunk: Vec<u8> = FILE_BODY[..1024].to_vec();
    let stream = futures_util::stream::iter(vec![
        Ok::<Vec<u8>, std::io::Error>(chunk),
        Err(std::io::Error::other("simulated mid-stream disconnect")),
    ]);
    Response::new(Body::from_stream(stream))
}

/// HEAD pretends resume is possible; GET always returns 416. Verifies dlm
/// doesn't loop on a non-retryable status during a resume attempt.
async fn always_416(method: Method, _path: Path<String>) -> Response {
    if method == Method::HEAD {
        return head_metadata(FILE_BODY);
    }
    StatusCode::RANGE_NOT_SATISFIABLE.into_response()
}

/// Accepts the connection but never sends response headers (sleeps far longer
/// than any sane connection timeout). Verifies dlm bounds the wait for the
/// response and gives up instead of hanging when a server goes silent after
/// accepting the connection.
async fn stall_before_headers(_method: Method, _path: Path<String>) -> Response {
    tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    StatusCode::OK.into_response()
}

/// HEAD reports the full size immediately; GET sends response headers right
/// away but delays the first body byte by ~2s, emulating a slow-to-respond
/// server with a high time-to-first-byte. Verifies dlm waits for the body to
/// start (bounded by the read timeout) instead of aborting on the first chunk.
async fn slow_first_byte(method: Method, _path: Path<String>) -> Response {
    if method == Method::HEAD {
        return head_metadata(FILE_BODY);
    }
    let stream = futures_util::stream::once(async {
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;
        Ok::<Vec<u8>, std::io::Error>(FILE_BODY.to_vec())
    });
    let mut resp = Response::new(Body::from_stream(stream));
    resp.headers_mut().insert(
        CONTENT_LENGTH,
        HeaderValue::from_str(&FILE_BODY.len().to_string()).unwrap(),
    );
    resp
}

// ---------- helpers ----------

fn redirect(location: &str) -> Response {
    let mut resp = Response::new(Body::empty());
    *resp.status_mut() = StatusCode::FOUND;
    resp.headers_mut()
        .insert(LOCATION, HeaderValue::from_str(location).unwrap());
    resp
}

/// Empty-body HEAD response that advertises the size and range support of
/// `body`. Used by handlers that fake metadata for a resource served by a
/// different code path on GET.
fn head_metadata(body: &[u8]) -> Response {
    let mut resp = Response::new(Body::empty());
    let h = resp.headers_mut();
    h.insert(
        CONTENT_LENGTH,
        HeaderValue::from_str(&body.len().to_string()).unwrap(),
    );
    h.insert(ACCEPT_RANGES, HeaderValue::from_static("bytes"));
    resp
}

/// Serve `body`, honoring `Range: bytes=N-M` if present and `support_range`
/// is true. Sets Content-Length, optional Accept-Ranges + Content-Range.
fn serve_with_range(body: &'static [u8], headers: &HeaderMap, support_range: bool) -> Response {
    if support_range
        && let Some(range) = headers.get(RANGE).and_then(|v| v.to_str().ok())
        && let Some((start, end)) = parse_byte_range(range, body.len())
    {
        let slice = &body[start..=end];
        let mut resp = Response::new(Body::from(slice));
        *resp.status_mut() = StatusCode::PARTIAL_CONTENT;
        let h = resp.headers_mut();
        h.insert(
            CONTENT_LENGTH,
            HeaderValue::from_str(&slice.len().to_string()).unwrap(),
        );
        h.insert(
            CONTENT_RANGE,
            HeaderValue::from_str(&format!("bytes {start}-{end}/{}", body.len())).unwrap(),
        );
        h.insert(ACCEPT_RANGES, HeaderValue::from_static("bytes"));
        return resp;
    }
    let mut resp = Response::new(Body::from(body));
    let h = resp.headers_mut();
    h.insert(
        CONTENT_LENGTH,
        HeaderValue::from_str(&body.len().to_string()).unwrap(),
    );
    if support_range {
        h.insert(ACCEPT_RANGES, HeaderValue::from_static("bytes"));
    }
    resp
}

/// Parse `bytes=N-M` (M optional, defaults to total-1). Returns inclusive
/// range. dlm sends two shapes: a closed `bytes=0-0` metadata probe and an
/// open-ended `bytes=N-` resume; both are handled here. The `end.min(total-1)`
/// clamp models permissive real-world servers but is not exercised by dlm
/// itself, which no longer names an end past the body.
fn parse_byte_range(value: &str, total: usize) -> Option<(usize, usize)> {
    let rest = value.strip_prefix("bytes=")?;
    let (start, end) = rest.split_once('-')?;
    let start: usize = start.parse().ok()?;
    let end: usize = if end.is_empty() {
        total - 1
    } else {
        end.parse().ok()?
    };
    if start >= total || start > end {
        return None;
    }
    let end = end.min(total - 1);
    Some((start, end))
}
